import { get } from "http";
import {
  camelToSnake,
  snakeToCamel,
  capitalize,
  getAllStringCases,
  toCamelCase,
  toPlural,
  toSingular,
  toSnakeCase,
  toSpaceCase,
  toTitleCase,
  toCamelAndSnakeCase,
  toTitleCaseFromSnake,
  snakeToSnakeCapitalized,
  toSpaceTitleCaseFromSnake,
  getStringCases,
} from "./toCase";

const functions = {
  camelToSnake,
  snakeToCamel,
  capitalize,
  getAllStringCases,
  getStringCases,
  toCamelCase,
  toPlural,
  toSingular,
  toSnakeCase,
  toSpaceCase,
  toTitleCase,
  toCamelAndSnakeCase,
  toTitleCaseFromSnake,
  snakeToSnakeCapitalized,
  toSpaceTitleCaseFromSnake,
}
export {
  functions as default,
  camelToSnake,
  snakeToCamel,
  capitalize,
  getAllStringCases,
  getStringCases,
  toCamelCase,
  toPlural,
  toSingular,
  toSnakeCase,
  toSpaceCase,
  toTitleCase,
  toCamelAndSnakeCase,
  toTitleCaseFromSnake,
  snakeToSnakeCapitalized,
  toSpaceTitleCaseFromSnake,
}
